env:
  global:
    # COVERITY_SCAN_TOKEN
    # ** specific to your project **
    - secure: "R2SCZ__O6VlqXx9ubxr3tA"

addons:
  apt:
    packages:
      - cmake

    coverity_scan:
      project:
        name: "evanbowman/blind-jump-portable"
        description: ""
      notification_email: evan.a.bowman@gmail.com
      build_command_prepend: "cd build && ./set-desktop-toolchain.sh"
      build_command:   "make"
      branch_pattern: coverity-scan
